### PR TITLE
Add option to return HMTL object from visualize_text()

### PR DESCRIPTION
**Pull request by cdpierse**
Related issue: #544 

Adds flag `return_html`to `visualize_text()` that allows for the IPython HTML to be returned if the flag is set to `True`.

This is useful for cases where users may want to save the output from outside of a notebook etc. 

Usage looks like:

```python
from captum.attr import visualization as viz
.... # get attributions and data record


html_obj = viz.visualize_text([score_viz], return_html=True)
```

### CODE REVIEW

**Comment by bilalsal** [comment]
Thanks @cdpierse for putting this together!

@miguelmartin75 and @vivekmig: do you prefer we add return_html as a parameter? Or to always return the HTML content instead? (the routine currently does not return any value(.

**Comment by miguelmartin75** [comment]
> Thanks @cdpierse for putting this together!
> 
> @miguelmartin75 and @vivekmig: do you prefer we add return_html as a parameter? Or to always return the HTML content instead? (the routine currently does not return any value(.

I don't see any reason for why we couldn't always return HTML, since this method doesn't return anything and the HTML content is always being constructed.

**Comment by NarineK** [comment]
Feel free to return HTML. To avoid additional input argument, we can always return HTML and the user can chose to use it or not.

**Comment by cdpierse** [comment]
I've updated the PR so that HTML is now just always returned by default. Thanks.

**Pull request closed without merging**
