### PR TITLE
Avoid forward_hook under DataParallel

### PR DESCRIPTION
**Pull request by bilalsal**
Address same problem in the VQA Insights tutorial reported in issue #469

### CODE REVIEW

**Comment by NarineK** [comment]
Thank you for the PR @bilalsal ! I originally tested the notebook for VQA in 8 GPU environment and it worked fine back then. Did you test this in a GPU environment ? Maybe you can send me the details in a local thread.

**Comment by vivekmig** [comment]
@bilalsal @NarineK - Are we still planning to make this change to the tutorial or should we just close this PR? Alternatively, we can revert the other tutorial to the hook approach so that they are consistent.

**Comment by NarineK** [comment]
Since based on this change: https://github.com/pytorch/captum/commit/174ecbdf926a312d07c0ef728540455b1c2c1edb
VQA in the notebook already has some differences from the insights one I think we can close this PR and revisit if there will be any issues. What do you think, @bilalsal ?

**Comment by NarineK** [comment]
Closing it, since the issue got addressed

**Pull request closed without merging**
