### PR TITLE
Add missing type hints to master in accordance with PEP-0484

### PR DESCRIPTION
**Pull request by ProGamerGov**
While working on the Optim-WIP branch I discovered that some of the `__init__` functions lacked the `-> None` type hints that [PEP-0484](https://www.python.org/dev/peps/pep-0484/) specifies. It seemed pretty easy to automate a fix, so I went ahead and added them after figuring out the regex code I needed.

~~The failed test looks like it's unrelated to my changes. Mypy didn't show any issues when I ran it locally.~~

### CODE REVIEW

**Comment by ProGamerGov** [comment]
The failed tests look like it's unrelated to my changes.

**Review by NarineK — COMMENTED** [review]
Thank you for the fixes @ProGamerGov!
The differences in mypy behavior locally and on CircleCI could be related to different versions of mypy. It looks like on CircleCI it uses version: mypy-0.790.
What version do you use locally ?
cc: @vivekmig

**Comment by ProGamerGov** [comment]
@NarineK Looks like I'm using the same version of mypy, and today it's giving me the same error messages as in the CircleCI tests. No idea why it wasn't working yesterday, but I was able to fix the issues. There were a few type hinting bugs in the code that adding `-> None` exposed. 

I'm currently working on solving the final bug.

**Review by NarineK — APPROVED** [review]
Looks great! Thank you for working on this. It looks like the branch is out-of-date. Do you mind updating it ?

**Comment by ProGamerGov** [comment]
@NarineK I've merged the updates from the master branch into this branch!

**Comment by ProGamerGov** [comment]
I'm not quite sure how to solve the most recent mypy error caused by the last update to the master branch.

```
#!/bin/bash -eo pipefail
./scripts/run_mypy.sh

Success: no issues found in 50 source files
Success: no issues found in 15 source files
Success: no issues found in 6 source files
tests/attr/layer/test_layer_integrated_gradients.py:264: error: Value of type variable "ModuleOrModuleList" of "LayerIntegratedGradients" cannot be "object"
Found 1 error in 1 file (checked 65 source files)

Exited with code exit status 1

CircleCI received exit code 1
```

https://github.com/pytorch/captum/blob/master/tests/attr/layer/test_layer_integrated_gradients.py#L261-L266

**Comment by NarineK** [comment]
> I'm not quite sure how to solve the most recent mypy error caused by the lastest update to the master branch.
> 
> ```
> #!/bin/bash -eo pipefail
> ./scripts/run_mypy.sh
> 
> Success: no issues found in 50 source files
> Success: no issues found in 15 source files
> Success: no issues found in 6 source files
> tests/attr/layer/test_layer_integrated_gradients.py:264: error: Value of type variable "ModuleOrModuleList" of "LayerIntegratedGradients" cannot be "object"
> Found 1 error in 1 file (checked 65 source files)
> 
> Exited with code exit status 1
> 
> CircleCI received exit code 1
> ```
> 
> https://github.com/pytorch/captum/blob/master/tests/attr/layer/test_layer_integrated_gradients.py#L261-L266

@ProGamerGov, we made some change in LayerIG and now mypy errors should be fixed. Do you mind updating the branch ? I wonder if the error is still there. Sorry about that.

**Comment by ProGamerGov** [comment]
@NarineK The error is still present on the latest version of the master branch.

**Comment by NarineK** [comment]
> @NarineK The error is still present on the latest version of the master branch.

This is interesting! Thank you for the update @ProGamerGov! It doesn't seem that you touched anything related and previous PRs that we merged that rely on that code passed the tests.

Perhaps you can cast `layer` with a concrete type:
something like: cast(ModuleOrModuleList , emb_layers)

https://github.com/pytorch/captum/blob/master/tests/attr/layer/test_layer_integrated_gradients.py#L261

**Comment by ProGamerGov** [comment]
@NarineK I've already tried casting and it throws errors:

https://app.circleci.com/pipelines/github/pytorch/captum/2446/workflows/572cc30e-4859-4c91-8105-9a3a59b3f07e/jobs/11746

**Comment by ProGamerGov** [comment]
@NarineK I've made the suggested changes, so we'll see if that fixes the tests. You also accidentally edited my comment with your reply instead your own comment.

**Comment by NarineK** [comment]
> @NarineK I've made the suggested changes, so we'll see if that fixes the tests. You also accidentally edited my comment with your reply instead your own comment.

Oh, sorry about that :) Thank you for making the changes.

**Comment by ProGamerGov** [comment]
@NarineK All tests are passing now!

**Comment by NarineK** [comment]
> @NarineK All tests are passing now!

Awesome! Thank you!

**Pull request closed without merging**
