### PR TITLE
Update Captum Insight Instructions

### PR DESCRIPTION
**Pull request by bilalsal**
Updated installation instructions for Captum Insight as reported in #640

### CODE REVIEW

**Comment by NarineK** [comment]
cc: @Reubend

**Review by edward-io — APPROVED** [review]
Oops, didn't see this earlier. Looks good, thanks!

**Review by Reubend — APPROVED** [review]

**Comment by NarineK** [comment]
@bilalsal, since this is approved can we merge this ?

**Comment by vivekmig** [comment]
> Thanks @NarineK. Merging is still blocked on my end, possibly because CI failed, due to #669. I will check on this after #669 is resolved.

@bilalsal You should be able to override this failure and land, are you able to import this PR?

**Comment by bilalsal** [comment]
Thanks @vivekmig. I do not see a button to import the PR into Phabricator. Does that signal another issue?

**Pull request closed without merging**
